version: '3'

services:

  nginx:
    container_name: ngnix
    build: ./requirements/ngnix
    depends_on:
      - adminer
      - redis
      - hugo
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirments/wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
