version: '3'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
